import React, { useState } from 'react';
import { 
  FileCheck, 
  Printer, 
  Copy, 
  Check, 
  Download, 
  HelpCircle, 
  AlertOctagon,
  Briefcase
} from 'lucide-react';
import { ContractAnalysis } from '../types/legal';

interface AttorneyDossierProps {
  analysis: ContractAnalysis;
}

export const AttorneyDossier: React.FC<AttorneyDossierProps> = ({ analysis }) => {
  const [copied, setCopied] = useState(false);

  const generateMarkdownBrief = (): string => {
    return `# ATTORNEY INTAKE BRIEF — ${analysis.documentTitle.toUpperCase()}
Generated by LexiGuard AI on ${analysis.analyzedAt}
Overall Health Score: ${analysis.overallScore}/100 (${analysis.overallRating.replace('_', ' ')})

---

## 1. EXECUTIVE SUMMARY
${analysis.executiveSummary}

## 2. TOP RED FLAGS & HIGH-EXPOSURE CLAUSES
${analysis.attorneyBrief.topRedFlags.map((rf, i) => `${i + 1}. ${rf}`).join('\n')}

## 3. POINTED QUESTIONS FOR LEGAL COUNSEL
${analysis.attorneyBrief.questionsForCounsel.map((q, i) => `${i + 1}. ${q}`).join('\n')}

## 4. NEGOTIATION PRIORITIES & STRATEGY
${analysis.attorneyBrief.negotiationPriorities.map((p, i) => `${i + 1}. ${p}`).join('\n')}

## 5. SUGGESTED ADDENDUMS & RIDERS
${analysis.attorneyBrief.suggestedAddendums.map((a) => `- [ ] ${a}`).join('\n')}

## 6. CRITICAL TIMELINES & DEADLINES
${analysis.timelines.map((t) => `- **${t.event}**: ${t.timeline} (${t.consequence})`).join('\n')}

---
*Notice: This brief was automatically compiled by LexiGuard AI for informational triage and attorney preparation purposes.*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownBrief());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const brief = generateMarkdownBrief();
    const blob = new Blob([brief], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Attorney_Brief_${analysis.documentTitle.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <section aria-labelledby="dossier-heading" className="animate-fade-in">
      {/* Top Header & Actions */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h2 id="dossier-heading" style={{ fontSize: '1.35rem', margin: 0, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <Briefcase size={22} color="var(--brand-primary)" />
            Attorney Consultation Dossier Generator
          </h2>
          <p style={{ fontSize: '0.875rem', color: 'var(--text-secondary)', margin: 0 }}>
            Structured briefing packet designed to maximize efficiency and minimize hourly billing during your lawyer consultation.
          </p>
        </div>

        <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={handleCopyMarkdown}
            id="btn-copy-brief"
          >
            {copied ? <Check size={14} color="#10b981" /> : <Copy size={14} />}
            <span>{copied ? 'Copied Brief' : 'Copy Markdown'}</span>
          </button>
          <button
            type="button"
            className="btn btn-secondary btn-sm"
            onClick={handleDownloadMarkdown}
            id="btn-download-brief"
          >
            <Download size={14} />
            <span>Download .MD</span>
          </button>
          <button
            type="button"
            className="btn btn-primary btn-sm"
            onClick={handlePrint}
            id="btn-print-brief"
          >
            <Printer size={14} />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Structured Printable Brief Container */}
      <div 
        className="glass-panel" 
        style={{ 
          padding: '2rem', 
          background: 'var(--bg-surface)', 
          border: '1px solid var(--border-strong)',
          display: 'flex',
          flexDirection: 'column',
          gap: '1.75rem'
        }}
        id="printable-dossier"
      >
        {/* Dossier Header Info */}
        <div style={{ borderBottom: '2px solid var(--border-subtle)', paddingBottom: '1.25rem', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
          <div>
            <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--brand-primary)', textTransform: 'uppercase', letterSpacing: '0.08em' }}>
              Confidential Legal Triage Packet
            </span>
            <h3 style={{ fontSize: '1.5rem', margin: '0.25rem 0' }}>
              {analysis.documentTitle}
            </h3>
            <span style={{ fontSize: '0.825rem', color: 'var(--text-tertiary)' }}>
              Analyzed: {analysis.analyzedAt} • Health Score: {analysis.overallScore}/100
            </span>
          </div>
          <span className={`badge badge-${analysis.overallScore < 50 ? 'critical' : 'info'}`} style={{ fontSize: '0.85rem', padding: '0.4rem 0.8rem' }}>
            {analysis.overallRating.replace('_', ' ')}
          </span>
        </div>

        {/* 1. Executive Summary */}
        <div>
          <h4 style={{ fontSize: '1.05rem', color: 'var(--text-primary)', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <FileCheck size={17} color="var(--brand-primary)" />
            1. Executive Synthesis for Counsel
          </h4>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', lineHeight: 1.6, margin: 0 }}>
            {analysis.executiveSummary}
          </p>
        </div>

        {/* 2. Top Red Flags */}
        <div>
          <h4 style={{ fontSize: '1.05rem', color: 'var(--risk-critical)', marginBottom: '0.65rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <AlertOctagon size={17} />
            2. High-Exposure Contractual Hazards
          </h4>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            {analysis.attorneyBrief.topRedFlags.map((flag, idx) => (
              <div 
                key={idx}
                style={{
                  background: 'var(--risk-critical-bg)',
                  padding: '0.75rem 1rem',
                  borderRadius: 'var(--radius-sm)',
                  border: '1px solid var(--risk-critical-border)',
                  fontSize: '0.865rem',
                  color: 'var(--text-primary)',
                  display: 'flex',
                  gap: '0.5rem'
                }}
              >
                <strong style={{ color: 'var(--risk-critical)' }}>#{idx + 1}</strong>
                <span>{flag}</span>
              </div>
            ))}
          </div>
        </div>

        {/* 3. Pointed Questions to Ask Your Lawyer */}
        <div>
          <h4 style={{ fontSize: '1.05rem', color: 'var(--text-primary)', marginBottom: '0.65rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
            <HelpCircle size={17} color="var(--brand-primary)" />
            3. Five Pointed Questions for Legal Counsel
          </h4>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            {analysis.attorneyBrief.questionsForCounsel.map((q, idx) => (
              <div 
                key={idx}
                style={{
                  background: 'var(--bg-surface-elevated)',
                  padding: '0.75rem 1rem',
                  borderRadius: 'var(--radius-sm)',
                  border: '1px solid var(--border-subtle)',
                  fontSize: '0.865rem',
                  color: 'var(--text-primary)',
                  display: 'flex',
                  gap: '0.5rem'
                }}
              >
                <strong style={{ color: 'var(--brand-primary)' }}>Q{idx + 1}:</strong>
                <span>{q}</span>
              </div>
            ))}
          </div>
        </div>

        {/* 4. Negotiation Priorities */}
        <div>
          <h4 style={{ fontSize: '1.05rem', color: 'var(--text-primary)', marginBottom: '0.65rem' }}>
            4. Recommended Redline Strategy & Priorities
          </h4>
          <ul style={{ paddingLeft: '1.25rem', display: 'flex', flexDirection: 'column', gap: '0.35rem', fontSize: '0.865rem', color: 'var(--text-secondary)' }}>
            {analysis.attorneyBrief.negotiationPriorities.map((item, idx) => (
              <li key={idx}>{item}</li>
            ))}
          </ul>
        </div>

        {/* 5. Suggested Riders & Addendums */}
        <div>
          <h4 style={{ fontSize: '1.05rem', color: 'var(--text-primary)', marginBottom: '0.65rem' }}>
            5. Suggested Standard Addendums
          </h4>
          <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
            {analysis.attorneyBrief.suggestedAddendums.map((addendum, idx) => (
              <span key={idx} className="badge badge-info" style={{ fontSize: '0.75rem', padding: '0.35rem 0.65rem' }}>
                + {addendum}
              </span>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};
