import { useState, useCallback, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, FileText, Download, Copy, Check, Briefcase } from 'lucide-react';
import { ClauseList } from '../components/ClauseList';
import { GotchasSummary } from '../components/GotchasSummary';
import { DisclaimerBanner } from '../components/DisclaimerBanner';
import { useAnalysis } from '../hooks/useAnalysis';

/**
 * Analysis page — shows clause-by-clause risk analysis, summary dashboard,
 * counter-drafts, gotchas summary, and Attorney Consultation Dossier exporter.
 */
export function AnalysisPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { status, analysis, error, isLoading, isAnalyzing, startAnalysis } = useAnalysis(id || null);
  const [dossierCopied, setDossierCopied] = useState(false);

  // Auto-trigger analysis when document is ready
  useEffect(() => {
    if (status === 'uploaded' && !isAnalyzing && !analysis) {
      const timer = setTimeout(() => startAnalysis(), 1000);
      return () => clearTimeout(timer);
    }
    if (status === 'analyzed' && !analysis && !isAnalyzing) {
      startAnalysis();
    }
  }, [status, isAnalyzing, analysis, startAnalysis]);

  const handleClauseClick = useCallback((clauseIndex: number) => {
    const el = document.getElementById(`clause-${clauseIndex}`);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'center' });
      const header = document.getElementById(`clause-header-${clauseIndex}`);
      header?.focus();
    }
  }, []);

  const generateDossierMarkdown = useCallback(() => {
    if (!analysis) return '';
    const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    
    let md = `# ATTORNEY CONSULTATION BRIEF & CONTRACT RISK AUDIT\n`;
    md += `**Platform:** LexiGuard AI (AI for Legal Assistance & Access)\n`;
    md += `**Document:** ${analysis.filename}\n`;
    md += `**Category:** ${analysis.documentType === 'freelance_services' ? 'Freelance Services' : 'Residential Lease'}\n`;
    md += `**Date:** ${dateStr}\n\n`;
    
    md += `## 1. EXECUTIVE RISK SUMMARY\n`;
    md += `- Total Analyzed Clauses: ${analysis.summary.total}\n`;
    md += `- Critical Liabilities (Unfavorable): ${analysis.summary.unfavorable}\n`;
    md += `- Cautionary Terms: ${analysis.summary.caution}\n`;
    md += `- Standard Terms: ${analysis.summary.standard}\n\n`;

    md += `## 2. KEY GOTCHAS & IMMEDIATE PITFALLS\n`;
    analysis.gotchas.forEach((g, i) => {
      md += `${i + 1}. **${g.title}** [${g.riskLevel}]: ${g.explanation}\n`;
    });
    md += `\n`;

    md += `## 3. CLAUSES FLAGGED FOR LEGAL COUNSEL REVIEW\n\n`;
    analysis.clauses
      .filter((c) => c.riskLevel === 'Unfavorable' || c.riskLevel === 'Caution')
      .forEach((c) => {
        md += `### Clause #${c.clauseIndex + 1}: ${c.clauseType} (Risk: ${c.riskLevel})\n`;
        md += `**Original Language:**\n> "${c.clauseText.replace(/\n/g, ' ')}"\n\n`;
        md += `**Identified Asymmetry / Risk:**\n${c.semanticDeltaExplanation || 'Deviates from market standard.'}\n\n`;
        if (c.nearestBenchmarkText) {
          md += `**Market Standard Comparison:**\n${c.nearestBenchmarkText}\n\n`;
        }
        if (c.counterDraft) {
          md += `**Recommended Counter-Proposal:**\n"${c.counterDraft}"\n\n`;
        }
        md += `**Strategic Inquiries for Attorney:**\n`;
        md += `1. Is this limitation/indemnity enforceable under applicable state law?\n`;
        md += `2. Would executing our proposed counter-draft adequately safeguard our rights without jeopardizing the deal?\n\n`;
        md += `---\n\n`;
      });

    md += `*DISCLAIMER: This dossier was generated by LexiGuard AI for informational preparation. It does not constitute formal legal representation.*`;
    return md;
  }, [analysis]);

  const handleCopyDossier = useCallback(async () => {
    const text = generateDossierMarkdown();
    try {
      await navigator.clipboard.writeText(text);
      setDossierCopied(true);
      setTimeout(() => setDossierCopied(false), 2500);
    } catch {
      const ta = document.createElement('textarea');
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setDossierCopied(true);
      setTimeout(() => setDossierCopied(false), 2500);
    }
  }, [generateDossierMarkdown]);

  const handleDownloadDossier = useCallback(() => {
    const text = generateDossierMarkdown();
    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LexiGuard_Attorney_Dossier_${analysis?.filename.replace(/\.[^/.]+$/, '')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [analysis, generateDossierMarkdown]);

  // Loading state
  if (isLoading || isAnalyzing || (!analysis && !error)) {
    return (
      <div className="page">
        <div className="container">
          <div className="loading-overlay">
            <div className="spinner" aria-label="Analyzing document" />
            <div>
              <p style={{ fontWeight: 600, color: 'var(--color-text-primary)' }}>
                {isAnalyzing ? 'Auditing Agreement with Gemini 2.5 Flash...' : 'Extracting Clauses & Benchmark Embeddings...'}
              </p>
              <p style={{ marginTop: 'var(--space-sm)', color: 'var(--color-text-tertiary)', fontSize: 'var(--font-size-xs)' }}>
                {isAnalyzing
                  ? 'Comparing clauses against 32+ market standards via pgvector & drafting counter-proposals'
                  : 'Sanitizing text and identifying clause boundaries'}
              </p>
            </div>
            <div className="progress-bar" style={{ maxWidth: '300px' }}>
              <div
                className="progress-fill"
                style={{ width: isAnalyzing ? '75%' : '35%' }}
              />
            </div>
          </div>
        </div>
      </div>
    );
  }

  // Error state
  if (error) {
    return (
      <div className="page">
        <div className="container">
          <div className="glass-card" style={{ maxWidth: '600px', margin: '0 auto', textAlign: 'center' }}>
            <p style={{ color: 'var(--color-unfavorable)', fontWeight: 600, marginBottom: 'var(--space-md)' }}>
              Analysis Failed
            </p>
            <p style={{ color: 'var(--color-text-secondary)', marginBottom: 'var(--space-lg)' }}>{error}</p>
            <button className="btn btn-primary" onClick={() => navigate('/')}>
              <ArrowLeft size={16} aria-hidden="true" /> Try Another Document
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (!analysis) return null;

  return (
    <div className="page">
      <div className="container">
        {/* Header with Dossier Export */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: 'var(--space-md)',
          marginBottom: 'var(--space-xl)'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 'var(--space-md)' }}>
            <button
              className="btn btn-ghost"
              onClick={() => navigate('/')}
              aria-label="Go back to upload page"
            >
              <ArrowLeft size={18} aria-hidden="true" />
            </button>
            <div>
              <h1 style={{
                fontSize: 'var(--font-size-xl)',
                fontWeight: 700,
                display: 'flex',
                alignItems: 'center',
                gap: 'var(--space-sm)',
              }}>
                <FileText size={22} aria-hidden="true" style={{ color: 'var(--color-accent)' }} />
                {analysis.filename}
              </h1>
              <p style={{ color: 'var(--color-text-secondary)', fontSize: 'var(--font-size-sm)', marginTop: '2px' }}>
                {analysis.documentType === 'freelance_services' ? 'Freelance Services Agreement' : 'Residential Lease'} •{' '}
                {analysis.clauses.length} clauses analyzed
              </p>
            </div>
          </div>

          {/* Attorney Dossier Actions */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <button
              type="button"
              className="btn btn-secondary"
              onClick={handleCopyDossier}
              aria-label="Copy attorney consultation dossier"
              style={{ display: 'inline-flex', alignItems: 'center', gap: '6px' }}
            >
              {dossierCopied ? <Check size={15} color="#059669" /> : <Copy size={15} />}
              <span>{dossierCopied ? 'Dossier Copied!' : 'Copy Attorney Brief'}</span>
            </button>
            <button
              type="button"
              className="btn btn-primary"
              onClick={handleDownloadDossier}
              aria-label="Download attorney consultation dossier as markdown"
              style={{ display: 'inline-flex', alignItems: 'center', gap: '6px' }}
            >
              <Briefcase size={15} />
              <Download size={14} />
              <span>Export Dossier</span>
            </button>
          </div>
        </div>

        {/* Disclaimer */}
        <div style={{ marginBottom: 'var(--space-xl)' }}>
          <DisclaimerBanner compact />
        </div>

        {/* Summary Dashboard */}
        <div className="summary-dashboard" role="region" aria-label="Analysis summary">
          <div className="glass-card summary-stat stat-total">
            <div className="stat-value">{analysis.summary.total}</div>
            <div className="stat-label">Total Clauses</div>
          </div>
          <div className="glass-card summary-stat stat-standard">
            <div className="stat-value">{analysis.summary.standard}</div>
            <div className="stat-label">Standard</div>
          </div>
          <div className="glass-card summary-stat stat-caution">
            <div className="stat-value">{analysis.summary.caution}</div>
            <div className="stat-label">Caution</div>
          </div>
          <div className="glass-card summary-stat stat-unfavorable">
            <div className="stat-value">{analysis.summary.unfavorable}</div>
            <div className="stat-label">Unfavorable</div>
          </div>
        </div>

        {/* Gotchas Summary */}
        <GotchasSummary
          gotchas={analysis.gotchas}
          onClauseClick={handleClauseClick}
        />

        {/* Clause-by-clause view */}
        <section style={{ marginTop: 'var(--space-2xl)' }} aria-label="Clause-by-clause analysis">
          <h2 style={{
            fontSize: 'var(--font-size-xl)',
            fontWeight: 700,
            marginBottom: 'var(--space-lg)',
          }}>
            Clause Analysis
          </h2>
          <ClauseList
            clauses={analysis.clauses}
            onClauseSelect={handleClauseClick}
          />
        </section>
      </div>
    </div>
  );
}
